//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_Andreev_423
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorRoleApplications
    {
        public int ApplicationId { get; set; }
        public int UserId { get; set; }
        public string Motivation { get; set; }
        public string Status { get; set; }
        public string AdminComment { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> ReviewedAt { get; set; }
        public Nullable<int> ReviewedByUserId { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
