//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_Andreev_423
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaints
    {
        public int ComplaintId { get; set; }
        public int ComplainerUserId { get; set; }
        public Nullable<int> TargetBookId { get; set; }
        public Nullable<int> TargetReviewId { get; set; }
        public string Reason { get; set; }
        public string Status { get; set; }
        public Nullable<int> ModeratorUserId { get; set; }
        public string DecisionComment { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> DecidedAt { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Users Users { get; set; }
        public virtual Reviews Reviews { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
