//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_Andreev_423
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UP_Andreev_423Entities : DbContext
    {
        public UP_Andreev_423Entities()
            : base("name=UP_Andreev_423Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuthorRoleApplications> AuthorRoleApplications { get; set; }
        public virtual DbSet<BookComplaints> BookComplaints { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<FreezeAppeals> FreezeAppeals { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<ReadingListItems> ReadingListItems { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
